name: decoding
channels:
  - pytorch
  - huggingface
  - nvidia
  - conda-forge
  - defaults
dependencies:
  - python=3.12
  - pandas=2
  - seaborn=0.13
  - matplotlib=3.8
  - numpy=1.26
  - transformers=4.40.1 # Careful as models assumes this version (could work with others but not tested)
  - pytorch=2.3
  - pytorch-cuda=12.1
  - pyarrow
  - pyyaml
  - pynvml # for checking gpu utilization
  - datasets=2.18
  - lightning=2.2
  - scikit-learn=1.4
  - pip
  - wordfreq=3.1
  - wandb=0.16
  - pre-commit
  - ruff
  - hydra-core=1.3
  - ipykernel
  - beartype>=0.17
  - mypy
  - pytorch-metric-learning=2.4
  - torchmetrics=1.3.1 # 1.3.2 falls on 'ClasswiseWrapper' object has no attribute 'preds'
  - pandas-stubs # for type checking
  - types-tqdm # for type checking
  - pip:
      - git+https://github.com/lacclab/process-onestop-sr-report.git  # if using ssh-key note to change this and all repos in the way
      - -e . # For development purposes
      - tap
      - rich

